# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'MentorAndMentees' do

pod 'AlamofireObjectMapper', '~> 2.1'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

end

